import type { Recommendation } from '@/types/models';

/**
 * Base statique M16 (§5.4, annexe E) : contenus versionnés, jamais générés dynamiquement.
 * Chaque item porte un niveau de preuve (A/B/C/D) et des sources (§18.1).
 * Tout item C/D contient une formulation d'incertitude — vérifié par test de cohérence.
 * Ton : prudent, non injonctif, jamais culpabilisant (§5.1).
 */
export const RECOMMENDATIONS: Recommendation[] = [
  /* ---------- Phase menstruelle (§5.4.1) ---------- */
  {
    id: 'men-act-gentle',
    phase: 'menstrual',
    category: 'activity',
    profileTags: ['all'],
    title: { fr: 'Mouvement doux', en: 'Gentle movement' },
    body: {
      fr: 'Marche, yoga ou étirements : l’activité physique douce peut aider à soulager les douleurs menstruelles. Restez à l’écoute de votre énergie, sans aucune obligation de performance.',
      en: 'Walking, yoga or stretching: gentle physical activity can help ease menstrual pain. Listen to your energy — no performance required.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['cochrane', 'acog'],
    contraindicationTags: [],
  },
  {
    id: 'men-nut-iron',
    phase: 'menstrual',
    category: 'nutrition',
    profileTags: ['all'],
    title: { fr: 'Fer et vitamine C', en: 'Iron and vitamin C' },
    body: {
      fr: 'Les pertes sanguines augmentent les besoins en fer. Associer des aliments riches en fer (légumineuses, viande, légumes verts) à une source de vitamine C favorise son absorption.',
      en: 'Blood loss increases iron needs. Pairing iron-rich foods (legumes, meat, leafy greens) with a source of vitamin C supports absorption.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['anses', 'who'],
    contraindicationTags: [],
  },
  {
    id: 'men-nut-caffeine',
    phase: 'menstrual',
    category: 'nutrition',
    profileTags: ['all'],
    title: { fr: 'Caféine avec modération', en: 'Caffeine in moderation' },
    body: {
      fr: 'Limiter l’excès de caféine pourrait réduire l’inconfort chez certaines personnes. Les données restent limitées : observez ce qui vous convient.',
      en: 'Limiting excess caffeine might reduce discomfort for some people. Evidence is limited: notice what works for you.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'men-micro-iron',
    phase: 'menstrual',
    category: 'micronutrients',
    profileTags: ['all'],
    title: { fr: 'Fer : jamais sans avis', en: 'Iron: never without advice' },
    body: {
      fr: 'En cas de règles abondantes, le statut en fer mérite attention. Ne vous supplémentez pas sans avis : demandez conseil à un professionnel de santé, surtout pour le fer.',
      en: 'With heavy periods, iron status deserves attention. Do not supplement without advice: ask a healthcare professional, especially for iron.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['who', 'anses'],
    contraindicationTags: [],
  },
  {
    id: 'men-micro-magnesium',
    phase: 'menstrual',
    category: 'micronutrients',
    profileTags: ['all'],
    title: { fr: 'Magnésium ?', en: 'Magnesium?' },
    body: {
      fr: 'Le magnésium est parfois évoqué pour l’inconfort menstruel, mais les preuves restent limitées. Si vous envisagez une supplémentation, demandez conseil à un professionnel.',
      en: 'Magnesium is sometimes mentioned for menstrual discomfort, but evidence remains limited. If you consider supplements, ask a professional first.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'men-hyd-water',
    phase: 'menstrual',
    category: 'hydration',
    profileTags: ['all'],
    title: { fr: 'Bien s’hydrater', en: 'Stay hydrated' },
    body: {
      fr: 'Maintenir une bonne hydratation peut atténuer certains maux de tête chez certaines personnes. Les repères généraux : environ 2 L d’eau par jour, à adapter.',
      en: 'Good hydration may ease some headaches for some people. General reference: about 2 L of water daily, to be adapted.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['efsa'],
    contraindicationTags: [],
  },
  {
    id: 'men-sleep-rest',
    phase: 'menstrual',
    category: 'sleep',
    profileTags: ['all'],
    title: { fr: 'Priorité au repos', en: 'Prioritise rest' },
    body: {
      fr: 'L’inconfort menstruel peut perturber le sommeil. Accordez-vous des nuits complètes et des moments de repos sans culpabilité.',
      en: 'Menstrual discomfort can disturb sleep. Allow yourself full nights and guilt-free rest.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'men-stress-heat',
    phase: 'menstrual',
    category: 'stress',
    profileTags: ['all'],
    title: { fr: 'Chaleur locale', en: 'Local heat' },
    body: {
      fr: 'Une bouillotte sur le bas-ventre est reconnue pour le confort des crampes. Simple, sans risque aux températures raisonnables.',
      en: 'A hot water bottle on the lower belly is recognised for cramp comfort. Simple and safe at reasonable temperatures.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'men-stress-breathing',
    phase: 'menstrual',
    category: 'stress',
    profileTags: ['all'],
    title: { fr: 'Respiration et relaxation', en: 'Breathing and relaxation' },
    body: {
      fr: 'Respiration lente ou relaxation peuvent apaiser l’inconfort chez certaines personnes. Les preuves sont limitées mais la pratique est sans risque.',
      en: 'Slow breathing or relaxation may soothe discomfort for some people. Evidence is limited but the practice is harmless.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'men-prod-lighter',
    phase: 'menstrual',
    category: 'productivity',
    profileTags: ['all'],
    title: { fr: 'Planifier plus léger', en: 'Plan lighter' },
    body: {
      fr: 'Cette phase est parfois associée à une énergie plus basse — c’est très individuel. Si c’est votre cas, planifier des tâches moins exigeantes peut aider.',
      en: 'This phase is sometimes associated with lower energy — highly individual. If that is you, planning less demanding tasks may help.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'men-well-selfcompassion',
    phase: 'menstrual',
    category: 'wellbeing',
    profileTags: ['all'],
    title: { fr: 'Autocompassion', en: 'Self-compassion' },
    body: {
      fr: 'Chaleur, confort, douceur envers soi : prendre soin de soi pendant les règles n’est pas un luxe, c’est de l’écoute.',
      en: 'Warmth, comfort, kindness to yourself: caring for yourself during your period is not a luxury, it is listening.',
    },
    evidenceLevel: 'D',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },

  /* ---------- Phase folliculaire (§5.4.2) ---------- */
  {
    id: 'fol-act-intensity',
    phase: 'follicular',
    category: 'activity',
    profileTags: ['all'],
    title: { fr: 'Fenêtre d’énergie', en: 'Energy window' },
    body: {
      fr: 'L’énergie est souvent perçue en hausse. Chez certaines personnes, cette phase peut être propice à l’intensité ou au renforcement — la littérature sur la périodisation hormonale reste émergente et hétérogène.',
      en: 'Energy is often perceived as rising. For some people this phase may suit higher intensity or strength work — research on hormonal periodisation is still emerging and mixed.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: ['sport_intensity'],
  },
  {
    id: 'fol-nut-protein',
    phase: 'follicular',
    category: 'nutrition',
    profileTags: ['all'],
    title: { fr: 'Protéines suffisantes', en: 'Enough protein' },
    body: {
      fr: 'Une alimentation variée avec des protéines suffisantes accompagne bien l’entraînement et la récupération.',
      en: 'A varied diet with sufficient protein supports training and recovery.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['anses'],
    contraindicationTags: [],
  },
  {
    id: 'fol-sleep-basics',
    phase: 'follicular',
    category: 'sleep',
    profileTags: ['all'],
    title: { fr: 'Régularité du sommeil', en: 'Sleep regularity' },
    body: {
      fr: 'Des horaires de coucher réguliers et 7 à 9 h de sommeil restent la base d’une bonne énergie, quelle que soit la phase.',
      en: 'Regular bedtimes and 7–9 h of sleep remain the basis of good energy, in any phase.',
    },
    evidenceLevel: 'A',
    sourceRefs: ['who'],
    contraindicationTags: [],
  },
  {
    id: 'fol-prod-creative',
    phase: 'follicular',
    category: 'productivity',
    profileTags: ['all'],
    title: { fr: 'Tâches exigeantes', en: 'Demanding tasks' },
    body: {
      fr: 'Beaucoup décrivent cette période comme dynamique : cela peut être un bon moment pour les tâches exigeantes ou créatives. C’est individuel — vos propres données vous le diront.',
      en: 'Many describe this period as dynamic: it may be a good time for demanding or creative tasks. It is individual — your own data will tell.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'fol-hyd-basics',
    phase: 'follicular',
    category: 'hydration',
    profileTags: ['all'],
    title: { fr: 'Hydratation de base', en: 'Baseline hydration' },
    body: {
      fr: 'Environ 2 L d’eau par jour selon les repères européens, davantage en cas d’activité physique ou de chaleur.',
      en: 'About 2 L of water daily per European guidance, more with exercise or heat.',
    },
    evidenceLevel: 'A',
    sourceRefs: ['efsa'],
    contraindicationTags: [],
  },

  /* ---------- Phase ovulatoire (§5.4.3) ---------- */
  {
    id: 'ovu-act-joints',
    phase: 'ovulatory',
    category: 'activity',
    profileTags: ['all'],
    title: { fr: 'Énergie haute, articulations à l’écoute', en: 'High energy, mind the joints' },
    body: {
      fr: 'L’énergie est généralement élevée. Certaines études évoquent une laxité ligamentaire accrue autour de l’ovulation — les données sont limitées ; un échauffement soigné reste une bonne idée.',
      en: 'Energy is generally high. Some studies suggest increased ligament laxity around ovulation — evidence is limited; careful warm-ups remain a good idea.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: ['sport_intensity'],
  },
  {
    id: 'ovu-fert-window',
    phase: 'ovulatory',
    category: 'fertility',
    profileTags: ['conceive'],
    title: { fr: 'Fenêtre fertile estimée', en: 'Estimated fertile window' },
    body: {
      fr: 'La fenêtre fertile s’étend environ de 5 jours avant l’ovulation au lendemain. C’est une estimation statistique, pas une certitude — et jamais un moyen de contraception.',
      en: 'The fertile window spans roughly 5 days before ovulation to the day after. It is a statistical estimate, not a certainty — and never a contraceptive method.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['eshre', 'nice'],
    contraindicationTags: [],
  },
  {
    id: 'ovu-prod-social',
    phase: 'ovulatory',
    category: 'productivity',
    profileTags: ['all'],
    title: { fr: 'Période sociale ?', en: 'Social peak?' },
    body: {
      fr: 'Cette période est souvent perçue comme sociale et énergique — c’est individuel et non systématique. Profitez-en si c’est votre cas.',
      en: 'This period is often perceived as social and energetic — individual and not systematic. Enjoy it if that is you.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'ovu-nut-basics',
    phase: 'ovulatory',
    category: 'nutrition',
    profileTags: ['all'],
    title: { fr: 'Bases solides', en: 'Solid basics' },
    body: {
      fr: 'Repas équilibrés et réguliers : les fondamentaux nutritionnels ne changent pas avec la phase.',
      en: 'Balanced, regular meals: nutrition fundamentals do not change with the phase.',
    },
    evidenceLevel: 'A',
    sourceRefs: ['anses'],
    contraindicationTags: [],
  },

  /* ---------- Phase lutéale (§5.4.4) ---------- */
  {
    id: 'lut-act-moderate',
    phase: 'luteal',
    category: 'activity',
    profileTags: ['all'],
    title: { fr: 'Activités modérées et récupération', en: 'Moderate activity and recovery' },
    body: {
      fr: 'Une baisse d’énergie est possible en fin de phase chez certaines personnes. Les activités modérées (marche, natation tranquille, yoga) et la récupération sont à valoriser.',
      en: 'Energy may dip late in this phase for some people. Moderate activity (walking, easy swimming, yoga) and recovery are worth prioritising.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'lut-nut-complex-carbs',
    phase: 'luteal',
    category: 'nutrition',
    profileTags: ['all'],
    title: { fr: 'Glucides complexes, repas réguliers', en: 'Complex carbs, regular meals' },
    body: {
      fr: 'Des repas réguliers avec des glucides complexes pourraient aider au confort prémenstruel — plausible mais à preuve limitée. Limiter sel, alcool et caféine peut aider en cas de sensibilité.',
      en: 'Regular meals with complex carbs might support premenstrual comfort — plausible but with limited evidence. Limiting salt, alcohol and caffeine may help if you are sensitive.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'lut-micro-calcium',
    phase: 'luteal',
    category: 'micronutrients',
    profileTags: ['all'],
    title: { fr: 'Calcium', en: 'Calcium' },
    body: {
      fr: 'Le calcium possède des données parmi les plus citées pour l’inconfort prémenstruel. Comme toujours pour une supplémentation : demandez conseil à un professionnel.',
      en: 'Calcium has some of the most cited data for premenstrual discomfort. As always with supplements: ask a professional first.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'lut-micro-b6',
    phase: 'luteal',
    category: 'micronutrients',
    profileTags: ['all'],
    title: { fr: 'Vitamine B6 ?', en: 'Vitamin B6?' },
    body: {
      fr: 'La vitamine B6 est parfois évoquée pour le syndrome prémenstruel, avec des preuves limitées. Ne pas se supplémenter sans avis professionnel.',
      en: 'Vitamin B6 is sometimes mentioned for PMS, with limited evidence. Do not supplement without professional advice.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'lut-sleep-hygiene',
    phase: 'luteal',
    category: 'sleep',
    profileTags: ['all'],
    title: { fr: 'Hygiène de sommeil renforcée', en: 'Stronger sleep hygiene' },
    body: {
      fr: 'Le sommeil peut être plus fragile avant les règles. Chambre fraîche, horaires réguliers, écrans limités le soir : les bases comptent double ici.',
      en: 'Sleep can be more fragile before your period. Cool room, regular schedule, fewer screens at night: the basics count double here.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['acog', 'nice'],
    contraindicationTags: [],
  },
  {
    id: 'lut-stress-relax',
    phase: 'luteal',
    category: 'stress',
    profileTags: ['all'],
    title: { fr: 'Relaxation et activité physique', en: 'Relaxation and activity' },
    body: {
      fr: 'L’activité physique et les techniques de relaxation ont un soutien raisonnable pour l’inconfort prémenstruel.',
      en: 'Physical activity and relaxation techniques have reasonable support for premenstrual discomfort.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['cochrane'],
    contraindicationTags: [],
  },
  {
    id: 'lut-prod-calm',
    phase: 'luteal',
    category: 'productivity',
    profileTags: ['all'],
    title: { fr: 'Tâches plus calmes en fin de phase', en: 'Calmer tasks late phase' },
    body: {
      fr: 'Certaines personnes préfèrent des tâches plus calmes en fin de phase lutéale. Ce n’est jamais une fatalité — observez vos propres tendances.',
      en: 'Some people prefer calmer tasks late in the luteal phase. Never a fate — observe your own patterns.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },
  {
    id: 'lut-well-kindness',
    phase: 'luteal',
    category: 'wellbeing',
    profileTags: ['all'],
    title: { fr: 'Douceur avec soi-même', en: 'Kindness to yourself' },
    body: {
      fr: 'Si la sensibilité augmente avant les règles, ce n’est ni une faiblesse ni une pathologie. La variabilité est grande d’une personne à l’autre.',
      en: 'If sensitivity rises before your period, it is neither weakness nor pathology. Variability between people is wide.',
    },
    evidenceLevel: 'D',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },

  /* ---------- Toutes phases : sexualité (information neutre, §5.4) ---------- */
  {
    id: 'any-sex-neutral',
    phase: 'any',
    category: 'sexuality',
    profileTags: ['all'],
    title: { fr: 'Libido et cycle', en: 'Libido and the cycle' },
    body: {
      fr: 'La libido peut varier au cours du cycle chez certaines personnes, sans que ce soit systématique. Aucune norme : votre rythme est le bon.',
      en: 'Libido may vary across the cycle for some people, though not systematically. No norm: your rhythm is the right one.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['acog'],
    contraindicationTags: [],
  },

  /* ---------- Profils spécifiques (§5.5) ---------- */
  {
    id: 'pcos-regular-activity',
    phase: 'any',
    category: 'activity',
    profileTags: ['pcos'],
    title: { fr: 'SOPK : régularité avant intensité', en: 'PCOS: consistency over intensity' },
    body: {
      fr: 'Avec un SOPK, une activité physique régulière a un bénéfice global bien soutenu — l’important est la régularité, pas la performance. Aucun objectif de poids n’est imposé ici.',
      en: 'With PCOS, regular physical activity has well-supported overall benefit — consistency matters, not performance. No weight goal is imposed here.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['eshre'],
    contraindicationTags: [],
  },
  {
    id: 'pcos-sleep-stress',
    phase: 'any',
    category: 'stress',
    profileTags: ['pcos'],
    title: { fr: 'SOPK : sommeil et stress', en: 'PCOS: sleep and stress' },
    body: {
      fr: 'Un rythme de vie régulier (sommeil, repas, gestion du stress) soutient l’équilibre global avec un SOPK. Le suivi spécialisé reste la référence.',
      en: 'A regular rhythm (sleep, meals, stress management) supports overall balance with PCOS. Specialist care remains the reference.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['eshre'],
    contraindicationTags: [],
  },
  {
    id: 'endo-heat-comfort',
    phase: 'any',
    category: 'wellbeing',
    profileTags: ['endometriosis'],
    title: { fr: 'Endométriose : stratégies de confort', en: 'Endometriosis: comfort strategies' },
    body: {
      fr: 'Chaleur locale et activité douce peuvent aider au confort de la douleur chez certaines personnes. Le suivi spécialisé est essentiel : ne restez pas seule avec des douleurs importantes.',
      en: 'Local heat and gentle activity may help pain comfort for some people. Specialist follow-up is essential: do not stay alone with significant pain.',
    },
    evidenceLevel: 'C',
    sourceRefs: ['eshre', 'has'],
    contraindicationTags: [],
  },
  {
    id: 'endo-pain-journal',
    phase: 'any',
    category: 'wellbeing',
    profileTags: ['endometriosis'],
    title: { fr: 'Journal de douleur pour consultation', en: 'Pain journal for consultations' },
    body: {
      fr: 'Documenter localisation, intensité et impact de la douleur aide beaucoup en consultation. Vous pouvez exporter vos données pour les partager avec votre équipe soignante.',
      en: 'Documenting pain location, intensity and impact helps a lot in consultations. You can export your data to share with your care team.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['eshre'],
    contraindicationTags: [],
  },
  {
    id: 'conceive-folate',
    phase: 'any',
    category: 'fertility',
    profileTags: ['conceive'],
    title: { fr: 'Acide folique : information clé', en: 'Folic acid: key information' },
    body: {
      fr: 'En cas de projet de grossesse, la supplémentation en acide folique (sur avis médical) est une recommandation de santé publique établie pour prévenir les anomalies de fermeture du tube neural. Parlez-en à un professionnel.',
      en: 'When planning pregnancy, folic acid supplementation (with medical advice) is an established public-health recommendation to prevent neural tube defects. Discuss it with a professional.',
    },
    evidenceLevel: 'A',
    sourceRefs: ['who', 'has'],
    contraindicationTags: [],
  },
  {
    id: 'conceive-lifestyle',
    phase: 'any',
    category: 'fertility',
    profileTags: ['conceive'],
    title: { fr: 'Hygiène de vie pro-fertilité', en: 'Fertility-friendly lifestyle' },
    body: {
      fr: 'Sommeil suffisant, activité modérée, alimentation équilibrée, tabac évité : des bases utiles. Sans conception après 12 mois d’essais (ou 6 mois après 35 ans), un avis médical est recommandé — information générale, pas un diagnostic.',
      en: 'Enough sleep, moderate activity, balanced diet, no smoking: useful foundations. Without conception after 12 months of trying (or 6 months after 35), medical advice is recommended — general information, not a diagnosis.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['eshre', 'nice'],
    contraindicationTags: [],
  },
  {
    id: 'peri-vasomotor',
    phase: 'any',
    category: 'wellbeing',
    profileTags: ['perimenopause'],
    title: { fr: 'Bouffées de chaleur : environnement frais', en: 'Hot flushes: cool environment' },
    body: {
      fr: 'Environnement frais, vêtements en couches et activité physique régulière aident à la gestion des symptômes vasomoteurs. En cas de gêne importante, un avis médical ouvre d’autres options.',
      en: 'A cool environment, layered clothing and regular physical activity help manage vasomotor symptoms. If they disrupt your life, medical advice opens further options.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['nice'],
    contraindicationTags: [],
  },
  {
    id: 'peri-sleep',
    phase: 'any',
    category: 'sleep',
    profileTags: ['perimenopause'],
    title: { fr: 'Sommeil en périménopause', en: 'Sleep in perimenopause' },
    body: {
      fr: 'Les sueurs nocturnes peuvent fragmenter le sommeil. Chambre fraîche et literie respirante aident ; parlez-en à un professionnel si le sommeil se dégrade durablement.',
      en: 'Night sweats can fragment sleep. A cool room and breathable bedding help; talk to a professional if sleep worsens durably.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['nice'],
    contraindicationTags: [],
  },
  {
    id: 'postpartum-rest',
    phase: 'any',
    category: 'wellbeing',
    profileTags: ['postpartum'],
    title: { fr: 'Post-partum : repos et soutien', en: 'Postpartum: rest and support' },
    body: {
      fr: 'Repos, soutien et hydratation passent avant tout le reste. Aucune pression : le retour de couches est imprévisible et c’est normal. Les professionnels de la périnatalité sont vos alliés.',
      en: 'Rest, support and hydration come before everything else. No pressure: the return of your cycle is unpredictable and that is normal. Perinatal professionals are your allies.',
    },
    evidenceLevel: 'B',
    sourceRefs: ['who', 'nice'],
    contraindicationTags: [],
  },
];
